// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerminalLog.Api.Data;

#nullable disable

namespace TerminalLog.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105130716_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TerminalLog.Api.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraChegada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraSaida")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroContainer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoCarga")
                        .HasColumnType("REAL");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoContainer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("TerminalLog.Api.Models.Doca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacidadePeso")
                        .HasColumnType("REAL");

                    b.Property<string>("CodigoDoca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Docas");
                });

            modelBuilder.Entity("TerminalLog.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TerminalLog.Api.Models.Agendamento", b =>
                {
                    b.HasOne("TerminalLog.Api.Models.Doca", "Doca")
                        .WithMany()
                        .HasForeignKey("DocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerminalLog.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doca");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
